version: '3.4'

services:
  
  lion.api:
    image: ${DOCKER_REGISTRY-}lionapi
    build:
      context: .
      dockerfile: src/Lion.API/Dockerfile

  lion.db:
    image: mysql:latest
    container_name: lion.db