name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Sonarqube Begin
      run: | 
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /o:gurame /k:gurame_lion /d:sonar.login=${{ secrets.X_SONAR_TOKEN }} /s:$GITHUB_WORKSPACE/.sonar/SonarQube.Analysis.xml
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test tests/Lion.UnitTests --no-build --verbosity normal --settings $GITHUB_WORKSPACE/.sonar/coverlet.runsettings --logger:trx
    - name: Sonarqube end
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.X_SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}